import { fetchCategories } from '@/http'
import { ICategory, ICollectionResponse } from '@/types'
import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { AxiosResponse } from "axios"

export default function Home({ }: NextPage) {
  return (
    <>
      <Head>
        <title>Coder Blog Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello world</h1>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  //categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories();

  console.log("categories", categories);

  return {
    props: {
      categories: {
        items: categories.data
      }
    }
  }
}
